#!/usr/bin/env ansible-playbook
- name: setup logins and secure sshd
  hosts: RPis
  remote_user: pi
  gather_facts: no
  vars:
    username: wuerzelchen
    user_groups: [ sudo ]
    log2ram_partitionsize: 100M
  tasks:
    - name: check connectivity
      ping:
    - name: enable ssh on startup
      systemd:
        state: started
        enabled: yes
        name: ssh
    - name: update root passwd from vault
      become: yes
      user:
        name: root
        password: "{{ root_password }}"
    - name: adding {{ username }} with passwd from vault
      become: true
      user:
        name: "{{ username }}"
        shell: /bin/bash
        groups: "{{ user_groups }}"
        append: yes
        password: "{{ user_password }}"
    - name: adding authorized_key for {{ username }}
      become: true
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      notify:
      - reboot
    - name: add log2ram gpg keys to apt
      become: true
      ansible.builtin.apt_key:
        url: https://azlux.fr/repo.gpg.key
        state: present
    - name: add log2ram repo to apt list
      become: true
      ansible.builtin.apt_repository:
        repo: deb http://packages.azlux.fr/debian/ buster main
        state: present
        filename: azlux.list
    - name: install log2ram
      ansible.builtin.apt:
        name: log2ram
        state: present
      become: true
      notify:
      - reboot
    - name: set log2ram partition size
      become: true
      lineinfile:
        dest: /etc/log2ram.conf
        regexp: "^SIZE="
        line: "SIZE={{ log2ram_partitionsize }}"
        state: present

  handlers:
    - name: reboot
      become: yes
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      notify: wait
    - name: wait
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      
