#!/usr/bin/env ansible-playbook
- name: setup logins and secure sshd
  hosts: masterNodes workerNodes
  remote_user: pi
  gather_facts: no
  vars:
    username: wuerzelchen
    user_groups: [ sudo ]
  tasks:
    - name: check connectivity
      ping:
    - name: enable ssh on startup
      systemd:
        state: started
        enabled: yes
        name: ssh
    - name: update root passwd from vault
      become: yes
      user:
        name: root
        password: "{{ root_password }}"
    - name: adding {{ username }} with passwd from vault
      become: true
      user:
        name: "{{ username }}"
        shell: /bin/bash
        groups: "{{ user_groups }}"
        append: yes
        password: "{{ user_password }}"
    - name: adding authorized_key for {{ username }}
      become: true
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      notify: reboot
  handlers:
    - name: reboot
      become: yes
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      notify: wait
    - name: wait
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      
