#!/usr/bin/env ansible-playbook
- name: install docker
  hosts: masterNodes workerNodes
  remote_user: wuerzelchen
  gather_facts: no
  tasks:
    - name: check connectivity
      ping:
    - name: install packages
      become: yes
      shell: curl -sSL get.docker.com | sh && \ sudo usermod wuerzelchen -aG docker
