#!/usr/bin/env ansible-playbook
- name: install docker
  hosts: masterNodes workerNodes
  remote_user: wuerzelchen
  gather_facts: no
  tasks:
    - name: check connectivity
      ping:
    - name: get packages
      get_url:
        url: https://get.docker.com
        dest: ./docker_install.sh
    - name: install packages
      become: yes
      shell: sh ./docker_install.sh && \ sudo usermod wuerzelchen -aG docker
