#!/usr/bin/env ansible-playbook
- name: prepare kubernetes installation
  hosts: wurzelMasters wurzelNodes
  remote_user: pi
  gather_facts: no
  tasks:
    - name: check connectivity
      ping:
    - name: append boot options
      become: yes
      lineinfile:
        dest: /boot/cmdline.txt
        backup: false
        backrefs: True
        state: present
        regexp: '(^dwc_otg\.lpm_enable\=0(\s+(?!cgroup_enable=cpuset)[\w=/\-\.\,]+)*)\s*$'
        line: '\1 cgroup_enable=memory cgroup_memory=1 cgroup_enable=cpuset'
      notify: reboot
  handlers:
    - name: reboot
      become: yes
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      notify: wait
    - name: wait
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
